"""Populate countries with UN member states

Revision ID: 91aa4f2372f6
Revises: a9d430950080
Create Date: 2025-09-17 15:08:16.808293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91aa4f2372f6'
down_revision: Union[str, None] = 'a9d430950080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create a connection to the database
    connection = op.get_bind()
    
    # UN Member States data with ISO-2 codes
    countries_data = [
        ('Afghanistan', 'AF'),
        ('Albania', 'AL'),
        ('Algeria', 'DZ'),
        ('Andorra', 'AD'),
        ('Angola', 'AO'),
        ('Antigua and Barbuda', 'AG'),
        ('Argentina', 'AR'),
        ('Armenia', 'AM'),
        ('Australia', 'AU'),
        ('Austria', 'AT'),
        ('Azerbaijan', 'AZ'),
        ('Bahamas', 'BS'),
        ('Bahrain', 'BH'),
        ('Bangladesh', 'BD'),
        ('Barbados', 'BB'),
        ('Belarus', 'BY'),
        ('Belgium', 'BE'),
        ('Belize', 'BZ'),
        ('Benin', 'BJ'),
        ('Bhutan', 'BT'),
        ('Bolivia', 'BO'),
        ('Bosnia and Herzegovina', 'BA'),
        ('Botswana', 'BW'),
        ('Brazil', 'BR'),
        ('Brunei Darussalam', 'BN'),
        ('Bulgaria', 'BG'),
        ('Burkina Faso', 'BF'),
        ('Burundi', 'BI'),
        ('Cabo Verde', 'CV'),
        ('Cambodia', 'KH'),
        ('Cameroon', 'CM'),
        ('Canada', 'CA'),
        ('Central African Republic', 'CF'),
        ('Chad', 'TD'),
        ('Chile', 'CL'),
        ('China', 'CN'),
        ('Colombia', 'CO'),
        ('Comoros', 'KM'),
        ('Congo', 'CG'),
        ('Costa Rica', 'CR'),
        ('Côte D\'Ivoire', 'CI'),
        ('Croatia', 'HR'),
        ('Cuba', 'CU'),
        ('Cyprus', 'CY'),
        ('Czechia', 'CZ'),
        ('Democratic People\'s Republic of Korea', 'KP'),
        ('Democratic Republic of the Congo', 'CD'),
        ('Denmark', 'DK'),
        ('Djibouti', 'DJ'),
        ('Dominica', 'DM'),
        ('Dominican Republic', 'DO'),
        ('Ecuador', 'EC'),
        ('Egypt', 'EG'),
        ('El Salvador', 'SV'),
        ('Equatorial Guinea', 'GQ'),
        ('Eritrea', 'ER'),
        ('Estonia', 'EE'),
        ('Eswatini', 'SZ'),
        ('Ethiopia', 'ET'),
        ('Fiji', 'FJ'),
        ('Finland', 'FI'),
        ('France', 'FR'),
        ('Gabon', 'GA'),
        ('Gambia', 'GM'),
        ('Georgia', 'GE'),
        ('Germany', 'DE'),
        ('Ghana', 'GH'),
        ('Greece', 'GR'),
        ('Grenada', 'GD'),
        ('Guatemala', 'GT'),
        ('Guinea', 'GN'),
        ('Guinea Bissau', 'GW'),
        ('Guyana', 'GY'),
        ('Haiti', 'HT'),
        ('Honduras', 'HN'),
        ('Hungary', 'HU'),
        ('Iceland', 'IS'),
        ('India', 'IN'),
        ('Indonesia', 'ID'),
        ('Iran (Islamic Republic of)', 'IR'),
        ('Iraq', 'IQ'),
        ('Ireland', 'IE'),
        ('Israel', 'IL'),
        ('Italy', 'IT'),
        ('Jamaica', 'JM'),
        ('Japan', 'JP'),
        ('Jordan', 'JO'),
        ('Kazakhstan', 'KZ'),
        ('Kenya', 'KE'),
        ('Kiribati', 'KI'),
        ('Kuwait', 'KW'),
        ('Kyrgyzstan', 'KG'),
        ('Lao People\'s Democratic Republic', 'LA'),
        ('Latvia', 'LV'),
        ('Lebanon', 'LB'),
        ('Lesotho', 'LS'),
        ('Liberia', 'LR'),
        ('Libya', 'LY'),
        ('Liechtenstein', 'LI'),
        ('Lithuania', 'LT'),
        ('Luxembourg', 'LU'),
        ('Madagascar', 'MG'),
        ('Malawi', 'MW'),
        ('Malaysia', 'MY'),
        ('Maldives', 'MV'),
        ('Mali', 'ML'),
        ('Malta', 'MT'),
        ('Marshall Islands', 'MH'),
        ('Mauritania', 'MR'),
        ('Mauritius', 'MU'),
        ('Mexico', 'MX'),
        ('Micronesia (Federated States of)', 'FM'),
        ('Monaco', 'MC'),
        ('Mongolia', 'MN'),
        ('Montenegro', 'ME'),
        ('Morocco', 'MA'),
        ('Mozambique', 'MZ'),
        ('Myanmar', 'MM'),
        ('Namibia', 'NA'),
        ('Nauru', 'NR'),
        ('Nepal', 'NP'),
        ('Netherlands', 'NL'),
        ('New Zealand', 'NZ'),
        ('Nicaragua', 'NI'),
        ('Niger', 'NE'),
        ('Nigeria', 'NG'),
        ('North Macedonia', 'MK'),
        ('Norway', 'NO'),
        ('Oman', 'OM'),
        ('Pakistan', 'PK'),
        ('Palau', 'PW'),
        ('Panama', 'PA'),
        ('Papua New Guinea', 'PG'),
        ('Paraguay', 'PY'),
        ('Peru', 'PE'),
        ('Philippines', 'PH'),
        ('Poland', 'PL'),
        ('Portugal', 'PT'),
        ('Qatar', 'QA'),
        ('Republic of Korea', 'KR'),
        ('Republic of Moldova', 'MD'),
        ('Romania', 'RO'),
        ('Russian Federation', 'RU'),
        ('Rwanda', 'RW'),
        ('Saint Kitts and Nevis', 'KN'),
        ('Saint Lucia', 'LC'),
        ('Saint Vincent and the Grenadines', 'VC'),
        ('Samoa', 'WS'),
        ('San Marino', 'SM'),
        ('Sao Tome and Principe', 'ST'),
        ('Saudi Arabia', 'SA'),
        ('Senegal', 'SN'),
        ('Serbia', 'RS'),
        ('Seychelles', 'SC'),
        ('Sierra Leone', 'SL'),
        ('Singapore', 'SG'),
        ('Slovakia', 'SK'),
        ('Slovenia', 'SI'),
        ('Solomon Islands', 'SB'),
        ('Somalia', 'SO'),
        ('South Africa', 'ZA'),
        ('South Sudan', 'SS'),
        ('Spain', 'ES'),
        ('Sri Lanka', 'LK'),
        ('Sudan', 'SD'),
        ('Suriname', 'SR'),
        ('Sweden', 'SE'),
        ('Switzerland', 'CH'),
        ('Syrian Arab Republic', 'SY'),
        ('Tajikistan', 'TJ'),
        ('Thailand', 'TH'),
        ('Timor-Leste', 'TL'),
        ('Togo', 'TG'),
        ('Tonga', 'TO'),
        ('Trinidad and Tobago', 'TT'),
        ('Tunisia', 'TN'),
        ('Türkiye', 'TR'),
        ('Turkmenistan', 'TM'),
        ('Tuvalu', 'TV'),
        ('Uganda', 'UG'),
        ('Ukraine', 'UA'),
        ('United Arab Emirates', 'AE'),
        ('United Kingdom of Great Britain and Northern Ireland', 'GB'),
        ('United Republic of Tanzania', 'TZ'),
        ('United States of America', 'US'),
        ('Uruguay', 'UY'),
        ('Uzbekistan', 'UZ'),
        ('Vanuatu', 'VU'),
        ('Venezuela, Bolivarian Republic of', 'VE'),
        ('Viet Nam', 'VN'),
        ('Yemen', 'YE'),
        ('Zambia', 'ZM'),
        ('Zimbabwe', 'ZW')
    ]
    
    # Insert countries data
    countries_table = sa.table('countries',
        sa.column('name', sa.String),
        sa.column('iso_code', sa.String),
        sa.column('has_visited', sa.Boolean),
        sa.column('visit_year', sa.Integer)
    )
    
    for name, iso_code in countries_data:
        connection.execute(
            countries_table.insert().values(
                name=name,
                iso_code=iso_code,
                has_visited=False,
                visit_year=None
            )
        )


def downgrade() -> None:
    # Remove all countries data
    connection = op.get_bind()
    connection.execute(sa.text("DELETE FROM countries"))
